version: '3.9'
services:
  python_flask:
    build: ./python_flask
    ports:
      - '8000:5000'
  kotlin_ktor:
    build: ./kotlin_ktor
    ports:
      - '8001:8080'
    depends_on:
      db:
        condition: service_healthy
  julia_genie:
    build: ./julia_genie
    ports:
      - '8002:8000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d exampledb -U docker']
      interval: 5s
