# Use an official Ruby runtime as a parent image
FROM ruby:3.2.2-alpine

# Set the working directory to /app
WORKDIR /app

# Install necessary packages
RUN apk add --no-cache --virtual build-dependencies build-base postgresql-dev

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install dependencies
RUN bundle install --without development test

# Copy the rest of the application code into the container
COPY . .

EXPOSE 8010:3001

CMD ["bundle", "install"]
CMD ["rails", "db:migrate"]

# Start the Rails server
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3001"]
